### PR TITLE
Added num_of_rooms to hotel and underlined PK

### PR DESCRIPTION
**Pull request by MichiasShiferaw**

### CODE REVIEW

**Review by kevinluong21 — CHANGES_REQUESTED** [review]
Hotel chain needs a number of hotels attribute.

**Review by kevinluong21 — CHANGES_REQUESTED** [review]
Hotel chain needs a number of hotels attribute. Is it possible to seperate the primary keys of the address into separate lines?

**Comment by MichiasShiferaw** [comment]
> The hotel_phone and address relations should be changed to phone and address_info to be consistent with the ER diagram.

The names of the (final/handwritten) ER diagram will be changed not relational schema.

**Comment by MichiasShiferaw** [comment]
> I'd also do a last quick check to compare the attributes from the project description and the diagram (I'm not saying they're wrong, but just a quick check to make sure all the attributes that are needed are in the diagram).

@AlexSteeves revise the relational schema to the project description to ensure that all relations, keys and attributes are provided.

I will the same with the ER diagram.

**Comment by kevinluong21** [comment]
The booking_info and renting_info relation needs to have the same PK as its identifying sets!!!

**Comment by kevinluong21** [comment]
The address attribute in hotel_chain will have to be split into 3 attributes where each references to the street_number, street_name, and postal code. (Honestly, I'm not exactly sure we are using an address_info entity/relation if complex attributes get flattened anyways. Complex attributes like multi-valued attributes should be separate entities.)

**Comment by kevinluong21** [comment]
If you have hotel_id and phone_number as unique primary keys, you cannot have multiple phone numbers for different departments because it would have a duplicate hotel_id.

**Comment by kevinluong21** [comment]
There are a lot of attribute name discrepancies. Please make sure the attributes from the ER diagram and the relation schema match.

**Comment by kevinluong21** [comment]
full_name must be flattened since it is a complex attribute

**Review by kevinluong21 — CHANGES_REQUESTED** [review]
- The booking_info and renting_info relation needs to have the same PK as its identifying sets along with its own IDs (its PK aren't underlined)!!!
- The address attribute in hotel_chain will have to be split into 3 attributes where each references to the street_number, street_name, and postal code. (Honestly, I'm not exactly sure why we are using an address_info entity/relation if complex attributes get flattened anyways. Complex attributes like multi-valued attributes should be separate entities.)
- The attribute 'expendable' in room_category in the ER diagram and the relation schema should be '**extendable**'.
- If you have hotel_id and phone_number as unique primary keys, you cannot have multiple phone numbers for different departments because it would have a duplicate hotel_id.
- There are some attribute name discrepancies. Please make sure the attributes from the ER diagram and the relation schema match.
- full_name must be flattened since it is a complex attribute

**Comment by MichiasShiferaw** [comment]
> * If you have hotel_id and phone_number as unique primary keys, you cannot have multiple phone numbers for different departments because it would have a duplicate hotel_id.

The idea was that there are one or more phone numbers per department of a hotel
 
For instance, Hotel0, can be comprised of value
 ( 123123123, **management**),
 ( 999999999, accounting),
 ( 1234567890, hr),
 ( 888888888, **management** ),
 ( 777777777, **it**),
 ( 333333333, **it**),
 ( 111111111, **it**)
);
 
Notice that there are two different numbers for management, as well as IT.

**Comment by kevinluong21** [comment]
> > * If you have hotel_id and phone_number as unique primary keys, you cannot have multiple phone numbers for different departments because it would have a duplicate hotel_id.
> 
> The idea was that there are one or more phone numbers per department of a hotel
> 
> For instance, Hotel0, can be comprised of value ( 123123123, **management**), ( 999999999, accounting), ( 1234567890, hr), ( 888888888, **management** ), ( 777777777, **it**), ( 333333333, **it**), ( 111111111, **it**) );
> 
> Notice that there are two different numbers for management, as well as IT.

It still doesn't work because the ID of Hotel0 would have to be referenced in each of these numbers and because it is a PK, the system will reject it.

**Comment by MichiasShiferaw** [comment]
> * The attribute 'expendable' in room_category in the ER diagram and the relation schema should be '**extendable**'.

Changed.

**Comment by MichiasShiferaw** [comment]
> It still doesn't work because the ID of Hotel0 would have to be referenced in each of these numbers and because it is a PK, the system will reject it.

Please check the image below, and let me know what you think. 
hotel_phone

Note that all **phone_numbers** must be unique table-wide

**Comment by kevinluong21** [comment]
> > It still doesn't work because the ID of Hotel0 would have to be referenced in each of these numbers and because it is a PK, the system will reject it.
> 
> Please check the image below, and let me know what you think. hotel_phone
> 
> Note that all **phone_numbers** must be unique table-wide

oh! my bad. i didn't realize that was possible. thanks for telling me!

**Review by kevinluong21 — APPROVED** [review]

**Pull request closed without merging**
